Models/FilterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SupportTicketSystem.Models
{
    public class FilterViewModel
    {
        [Display(Name = "Priority")]
        public string SelectedPriority { get; set; }
        [Display(Name = "Status")]
        public string SelectedStatus { get; set; }
    }
}

Models/Ticket.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SupportTicketSystem.Models;

public class Ticket
{
    [Key]
    public int ID { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    public DateTime CreationDate { get; set; }

    [Required]
    public string Priority { get; set; }

    [Required]
    public string Status { get; set; }

    public string UserId { get; set; }

    [ValidateNever]
    public virtual ApplicationUser ApplicationUser { get; set; }

   
}

Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SupportTicketSystem.Data;
using SupportTicketSystem.Models;

namespace SupportTicketSystem.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class TicketController : Controller
    {
        private readonly SupportTicketSystemContext _context;

        public TicketController(SupportTicketSystemContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier); 

            // Find all tickets that belong to the currently logged in user
            var userTickets = await _context.Ticket.Where(t => t.UserId == loggedInUserId).ToListAsync();


            if (User.IsInRole("Admin"))
            {
                // If the user is an admin, find all tickets
                userTickets = await _context.Ticket.ToListAsync();
            }

            return View(userTickets);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Find the ticket with the specified ID
            var ticket = await _context.Ticket
                .FirstOrDefaultAsync(m => m.ID == id);


            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        public IActionResult Create()
        {
            // Get the ID of the currently logged in user
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier); 
            ViewBag.UserId = loggedInUserId;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,CreationDate,Priority,Status,UserId")] Ticket ticket)
        {
            // NOTE: we do need all the fields to be entered otherwise we wont process, and we will stay on the Create Screen.
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync(); 
                return RedirectToAction(nameof(Index));
            }
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(new CreateTicketViewModel() { UserId = loggedInUserId });
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
           
            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }

            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!User.IsInRole("Admin") && ticket.UserId != loggedInUserId)

            {
                return RedirectToAction(nameof(Index));
            }

            return View(ticket);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,ID,Title,Description,CreationDate,Priority,Status")] Ticket ticket) 
        {
            // The id parameter is used to check if the ticket exists in the database
            if (id != ticket.ID)
            {
                return NotFound();
            }

            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!User.IsInRole("Admin") && ticket.UserId != loggedInUserId)
            {
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid) 
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }

                // The DbUpdateConcurrencyException is thrown if the ticket does not exist in the database
                catch (DbUpdateConcurrencyException) 
                {
                    // Check if the ticket exists in the database
                    if (!TicketExists(ticket.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            // Find the ticket with the specified ID. The Include method is used to include the user that created the ticket
            var ticket = await _context.Ticket
                .FirstOrDefaultAsync(m => m.ID == id);


            if (ticket == null)
            {
                return NotFound();
            }

            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!User.IsInRole("Admin") && ticket.UserId != loggedInUserId)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(ticket);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) 
        {
            // Find the ticket with the specified ID
            var ticket = await _context.Ticket.FindAsync(id);
            // Fix the green swiggly line, to ensure that the ticket is not null, to prevent a cross-site request forgery attack
            if (ticket == null)
            {
                return NotFound();
            }
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!User.IsInRole("Admin") && ticket.UserId != loggedInUserId)
            {
                return RedirectToAction(nameof(Index));
            }

            _context.Ticket.Remove(ticket);



            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Ticket.Any(e => e.ID == id);

        }

        public IActionResult Filter()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Filter(FilterViewModel model)
        {
            
            IEnumerable<Ticket> filteredTickets = _context.Ticket.ToArray(); 

            // Define an array of filter properties, each containing the property name and its corresponding selected value from the model.
            var filterProperties = new[]
            {
                new { PropertyName = "Priority", PropertyValue = model.SelectedPriority },
                new { PropertyName = "Status", PropertyValue = model.SelectedStatus }
            };

            if (User.IsInRole("User"))
            {
                // If the user is not an admin, only show tickets that belong to the currently logged in user
                filteredTickets = filteredTickets.Where(t => t.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier));

            }

            
            foreach (var filter in filterProperties)
            {
                
                if (!string.IsNullOrEmpty(filter.PropertyValue))
                {
                    // Filter the tickets based on the selected filter properties
                    filteredTickets = filteredTickets.Where(t => t.GetType().GetProperty(filter.PropertyName)!.GetValue(t, null)!.ToString() == filter.PropertyValue);

                }
            }

            var filteredTicketList = filteredTickets.ToList();
            return View("Index", filteredTicketList);
        }
    }
}

Views/Ticket/Create.cshtml
@model Ticket

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ticket</h4>
<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <select asp-for="Priority" class="form-control">
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                </select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="Open">Open</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Closed">Closed</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="UserId" value="@ViewBag.UserId" />
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ticket/Delete.cshtml
@model SupportTicketSystem.Models.Ticket

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <!-- Display ticket details using DisplayFor helper -->
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <!-- Form for deleting the ticket -->
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Ticket/Details.cshtml
@model SupportTicketSystem.Models.Ticket

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Ticket/Edit.cshtml
@model SupportTicketSystem.Models.Ticket

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <select asp-for="Priority" class="form-control">
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                </select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="Open">Open</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Closed">Closed</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="UserId" />
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ticket/Filter.cshtml
@model SupportTicketSystem.Models.FilterViewModel

@{
    ViewData["Title"] = "Filter";
}

<h1>Filter</h1>

<form asp-action="Filter" method="post">
    <div class="form-group">
        <label asp-for="SelectedPriority" class="control-label">Priority</label>
        <select asp-for="SelectedPriority" class="form-control">
            <option value="">All</option>
            <option value="Low">Low</option>
            <option value="Medium">Medium</option>
            <option value="High">High</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="SelectedStatus" class="control-label">Status</label>
        <select asp-for="SelectedStatus" class="form-control">
            <option value="">All</option>
            <option value="Open">Open</option>
            <option value="In Progress">In Progress</option>
            <option value="Closed">Closed</option>
        </select>
    </div>
    <div class="form-group">
        <input type="submit" value="Filter" class="btn btn-primary" />
    </div>
</form>

Views/Ticket/Index.cshtml
@model IEnumerable<SupportTicketSystem.Models.Ticket>

@{
    ViewData["Title"] = "Tickets";
}

<h2>Tickets</h2>

@if (User.IsInRole("Admin"))
{
    <p>All Tickets (Admin View)</p>
}

else
{
    <p>Your Tickets (User View)</p>
}

@if (Model.Count() == 0)
{
    <p>You have no tickets given the conditions, either make one or check your filter settings</p>
}

<h5>Functions:</h5>
<p>
    <a asp-action="Create" asp-controller="Ticket" style="text-decoration: none;">Create New</a><br />
    <a asp-controller="Ticket" asp-action="Filter" style="text-decoration: none;">Filter Tickets</a>
</p>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priority)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priority)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>